name: build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        deno:
          - v1.x

    name: Test with Deno ${{ matrix.deno }}
    steps:
      - uses: actions/checkout@master

      - uses: denoland/setup-deno@main
        with:
          deno-version: ${{ matrix.deno }}

      - name: Print deno version
        run: deno --version

      - name: Check lint
        run: deno lint --unstable

      - name: Check format
        run: deno fmt --check

      - name: Run tests
        run: deno test --unstable --coverage=cov_profile

      - name: Print coverage
        run: deno coverage --unstable cov_profile
